[package]
name = "crossword-wasm"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-bindgen = "0.2.100"


[lib]
name = "crossword"
#test = true
# plugin = false
crate-type = ["cdylib", "rlib"] 

[[bin]]
name = "main"
path = "src/bin/main.rs"

